# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: LRA test

on:
  push:
    branches: [ master ]
    paths:
      - "rts/lra/**"
  pull_request:
    branches: [ master ]
    paths:
      - "rts/lra/**"

jobs:
  lra-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Narayana - build
      run: mvn clean install -DskipTests
    - name: LRA - build
      run: |
        cd rts/lra
        mvn clean install -DskipTests
    - name: LRA - test (tck/basic)
      run: |
        cd rts/lra/lra-test
        mvn clean install -Parq

